name: Salazar-Assignment8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: here
        run: pwd
      - name: Build with Maven 
        run: git clone https://github.com/Graylog2/graylog2-server
      - name: next step
        run: cd graylog2-server
      - name: next step
        run: git rev-parse HEAD
      - name: next step
        run: mvn test-compile -pl graylog2-server -am
      - name: next step
        run: mvn -pl graylog2-server test -Dtest=org.graylog2.alarmcallbacks.AlarmCallbackHistoryServiceImplTest#testSaveForDummySuccess
      - name: next step
        run: mvn -pl graylog2-server edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.graylog2.alarmcallbacks.AlarmCallbackHistoryServiceImplTest#testSaveForDummySuccess
        
